sudo: false
language: python
matrix:
  include:
  - python: 3.8
    env: TOX_ENV=pep8
  - python: 3.8
    env: TOX_ENV=py38
  - python: 3.8
    env: TOX_ENV=docs
  - python: 2.7
    env: TOX_ENV=py27
  - python: 3.6
    env: TOX_ENV=py36
install:
- pip install tox
script:
- tox -e $TOX_ENV
deploy:
  provider: pypi
  user: suse
  password:
    secure: FLx7KdGhYsPzXO9uLVBsP7DWFPhPzZTKEXaZ4SZv6PbV7xTXNi7w/EnlGcP4OcqSofQxgEfOSty8GZ3MWASdHuIYGSWj2l3jj7Acro12TcA/XozHCDDr2kOq8pAlnz7G9ehmwjP2MyzMxl0dTM6KfAlyswjmXhXt03HiMPH2Cmc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: openSUSE/py2pack
